
export const ADD_ARTICLE = "ADD_ARTICLE";
export const DELETE_ARTICLE = "DELETE_ARTICLE";


export const FETCH_ARTICLES = "FETCH_ARTICLES";
export const ARTICLES_FETCH_SUCCEEDED = "ARTICLES_FETCH_SUCCEEDED";
export const ARTICLES_FETCH_ERROR = "ARTICLES_FETCH_ERROR";


export const FETCH_TOKEN = "FETCH_TOKEN";
export const TOKEN_FETCH_SUCCEDED = "TOKEN_FETCH_SUCCEDED";
export const TOKEN_FETCH_ERROR = "TOKEN_FETCH_ERROR";

export const FETCH_USER = "FETCH_USER";
export const USER_FETCH_SUCCEDED = "USER_FETCH_SUCCEDED";
export const USER_FETCH_ERROR = "USER_FETCH_ERROR";
